#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
START=95
# shellcheck disable=SC2034
USE_PROCD=1

readonly raFunctions='/usr/lib/remote-agent/functions.sh'
if [ -s "$raFunctions" ]; then
# shellcheck source=../../usr/lib/remote-agent/functions.sh
	. "$raFunctions"
else
	logger -t 'remote-agent' 'error' "Remote-Agent Functions file ($raFunctions) not found!"
fi

start_service() {
	[ -f "$ADOPTED_FLAG" ] && return 0
	procd_open_instance
	procd_set_param respawn 300 5 5
	procd_set_param command /usr/libexec/remote-agent/enroll-runner
	procd_close_instance
}
