#!/bin/sh
# Capture DHCP Option 114 into /etc/remote-agent/dhcp114.url
[ -n "$opt114" ] || exit 0

readonly raFunctions='/usr/lib/remote-agent/functions.sh'
if [ -s "$raFunctions" ]; then
# shellcheck source=../../../lib/remote-agent/functions.sh
	. "$raFunctions"
else
	logger -t 'remote-agent' 'error' "Remote-Agent Functions file ($raFunctions) not found!"
fi

mkdir -p "$STATE_DIR"
echo "$opt114" > "$STATE_DIR/dhcp114.url"
chmod 600 "$STATE_DIR/dhcp114.url"
/etc/init.d/remote-agent-enroll restart >/dev/null 2>&1 || true
